app = "greedypig"

[build]
image = "registry.fly.io/greedypig"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "11155111"
CARTESI_CONTRACTS_APPLICATION_ADDRESS="0x1DB85D41E07212d6ffFA52b0753C12205A59A3bB"
CARTESI_CONTRACTS_APPLICATION_DEPLOYMENT_BLOCK_NUMBER="5800102"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS="0x27d0211c25e6C810Ae92D00bfF88896eaAacAAa7"
CARTESI_CONTRACTS_HISTORY_ADDRESS="0x4CA3556CBfE33aD99F86eb5A982e1592f072ab0c"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "3963384"
CARTESI_EPOCH_DURATION = "86400"
CARTESI_AUTH_MNEMONIC="uniform unveil air update test obey giant apart bid brush void love"
CARTESI_BLOCKCHAIN_HTTP_ENDPOINT="https://eth-sepolia.g.alchemy.com/v2/S0QCH1ePWS2pTlRtAsK0JsXQIAaNQB_W"
CARTESI_BLOCKCHAIN_WS_ENDPOINT="wss://eth-sepolia.g.alchemy.com/v2/S0QCH1ePWS2pTlRtAsK0JsXQIAaNQB_W"
CARTESI_POSTGRES_ENDPOINT="postgres://postgres:rlxxLjDW0qDXHl1@greedy-pig-database.flycast:5432"