app = "greedypig"

[build]
image = "registry.fly.io/greedypig"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "11155111"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0xA7Df33D87a1a6d9BE5037F44E323B12b755c31fb"
CARTESI_CONTRACTS_APPLICATION_DEPLOYMENT_BLOCK_NUMBER = "6064654"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0xA2a201EdC8e7056d134a6C17811c19Be116ADdDa"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0x86d87c0c06aAA06fCcaf92acc3bECD59438be91F"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "3963384"
CARTESI_EPOCH_DURATION = "86400"
CARTESI_AUTH_MNEMONIC="screen fence prize absurd acoustic sure view parade moment car bitter sick"
CARTESI_BLOCKCHAIN_HTTP_ENDPOINT="https://eth-sepolia.g.alchemy.com/v2/S0QCH1ePWS2pTlRtAsK0JsXQIAaNQB_W"
CARTESI_BLOCKCHAIN_WS_ENDPOINT="wss://eth-sepolia.g.alchemy.com/v2/S0QCH1ePWS2pTlRtAsK0JsXQIAaNQB_W"
CARTESI_POSTGRES_ENDPOINT="postgres://postgres:f52y9sLzrwjWeZ0@greedypig-database.flycast:5432"