version: "3.9"

services:
  authority-deployer:
    image: gbbabarros/rollups-hardhat:1.0.1
    command:
      [
        "deploy",
        "--network",
        "sepolia",
        "--export",
        "/home/node/rollups.json",
      ]
    volumes:
      - ./.deployments/sepolia:/home/node
    environment:
      - MNEMONIC="screen fence prize absurd acoustic sure view parade moment car bitter sick"
      - RPC_URL=https://eth-sepolia.g.alchemy.com/v2/q7fjK5eosDfEgAmoNXHHIXMjEomWECLk
      - NETWORK=sepolia
      - CHAIN_ID=11155111

  dapp-deployer:
    build:
      dockerfile_inline: |
          # syntax=docker.io/docker/dockerfile:1.4
          FROM gbbabarros/rollups-cli:1.0.1
          RUN apk update && apk add jq
          RUN <<EOF
          echo '
            #!/bin/sh
            if [ ! -f /deployments/sepolia/rollups.json ]; then
              echo "No authority defined"
              exit 1
            fi
            echo "Deploying DApp on network \"sepolia\" using consensus address \"$(cat /deployments/sepolia/rollups.json | jq -r '.contracts.Authority.address')\"..."
            cartesi-rollups create \
                --rpc "$RPC_URL" \
                --mnemonic "$MNEMONIC" \
                --deploymentFile "/deployments/sepolia/rollups.json" \
                --templateHashFile /var/opt/cartesi/machine-snapshots/image/hash \
                --outputFile "/deployments/sepolia/dapp.json" \
                --consensusAddress "$(cat /deployments/sepolia/rollups.json | jq -r '.contracts.Authority.address')"
          ' > deploy.sh
          EOF
          ENTRYPOINT [ "sh"]
          CMD ["deploy.sh" ]

    volumes:
      - ./.sunodo:/var/opt/cartesi/machine-snapshots:ro
      - ./.deployments:/deployments
    environment:
      - MNEMONIC="screen fence prize absurd acoustic sure view parade moment car bitter sick"
      - NETWORK=sepolia
      - RPC_URL=https://eth-sepolia.g.alchemy.com/v2/q7fjK5eosDfEgAmoNXHHIXMjEomWECLk
      - CHAIN_ID=11155111
